# App
spring.application.name=unievent
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/unievent_db
spring.datasource.username=postgres
spring.datasource.password=postgre123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT (must be Base64 encoded, min 32 chars)
app.jwt.secret=dW5pZXZlbnRfc3VwZXJfc2VjcmV0X2tleV9mb3Jfand0XzIwMjQ=
app.jwt.expiration=86400000